### ISSUE TITLE
getBounds() doesn't return valid object

### ISSUE THREAD

**Issue by v-echo** [ghybs/Leaflet.MarkerCluster.LayerSupport#12]
When calling getBounds() on a L.markerClusterGroup.layerSupport object, it returns an invalid object (missing the required properties). 

`cluster = L.markerClusterGroup.layerSupport();
cluster.addTo(map);
map.fitBounds(cluster.getBounds());
`

Above code works in the base plugin, if you take out the layerSupport part.

**Comment by ghybs** [comment]
Hi,

Thank you for your report.

Please does it work for you if you specify option [`singleAddRemoveBufferDuration: 0`](https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport#options)?

I suspect the delay to handle the `addLayer` breaks your code because you may not expect layerSupport to behave asynchronously.

Example: https://jsfiddle.net/3v7hd2vx/387/

**Comment by v-echo** [comment]
Hi,

Your suspicion seems to have been correct. With that option, it works properly now. 
Thanks for clearing it up.

**Comment by ghybs** [comment]
Thank you for your confirmation.

Related to #11, this `singleAddRemoveBufferDuration` option seems to be counter-intuitive compared to Leaflet.markercluster behaviour (without this plugin).

Hence it sounds like this case is an extra reason to turn that option off by default (i.e. use `0` as default value).
Will modify this plugin accordingly next time.

**Comment by ltog** [comment]
@ghybs : I just ran into this issue where I had to apply `singleAddRemoveBufferDuration: 0` as you described. I'm using version 1.0.5 of Leaflet.MarkerCluster.LayerSupport. Is this supposed to be fixed in this version? Since in my case it doesn't seem to be fixed...

Thank you for your work!

**Comment by ghybs** [comment]
Hi @Itog,

Thank you for your message!

No unfortunately I have not updated this lib yet. Hopefully I can do that soon.

Would gladly accept a PR in the meantime!

**Comment by ghybs** [comment]
Fixed in version [v2.0.0](https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport/releases/tag/v2.0.0)
