### ISSUE TITLE
Is chunkedloading possible?

### ISSUE THREAD

**Issue by elite123** [ghybs/Leaflet.MarkerCluster.LayerSupport#8]
I'm loading a large dataset and would like to display a progress bar, is it possible to use chunkedloading as per:

https://github.com/Leaflet/Leaflet.markercluster#chunked-addlayers-options

**Comment by ghybs** [comment]
Hi,

I think it should work without particular issue.
If it is not the case, then please provide an [MCVE](https://stackoverflow.com/help/mcve) (e.g. using [Leaflet Playground](http://playground-leaflet.rhcloud.com/), Plunker, JSFiddle, etc.) so that it is possible to investigate.

**Comment by ghybs** [comment]
Hi,

mm indeed it looks like only when directly adding a Layer Group into the MCG (with Layer Support) makes use of the `chunkedLoading` option.
https://jsfiddle.net/3v7hd2vx/297/

Adding / removing the Layer Group directly to / from the map uses individual layers addition / removal, which is much more computation intensive, and bypasses the `chunkedLoading`.

Therefore it looks like we should add more methods override to proxy Layer Groups, to make sure that we do not let their child single marker being added to MCG, but to call directly `addLayers`.

In the meantime, it looks like my other plugin [Leaflet.FeatureGroup.SubGroup](https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup) works as expected:
https://jsfiddle.net/3v7hd2vx/296/
